In [1]:
import os, sys
import pandas as pd
import numpy as np
from functools import reduce

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from Scripts import Data_Loader_Functions as dL
from Scripts import Results_Evaluation as rE
RESULTS = os.path.join(module_path, 'Results', 'Thesis')
DATA = os.path.join(module_path, 'Data', 'Augmented Data', 'Flexible Augmentation')

## Load relevant variables

In [55]:
pd.options.display.float_format = '{:,.1%}'.format

In [3]:
pivot = dL.create_pivot(os.path.join(DATA, 'group_2'), 'Session', 'Person', 'Session')
subjects = dL.create_pain_df(os.path.join(DATA, 'group_2'))['Person'].unique()

In [4]:
results = {}

## Metric & Type

In [ ]:
metric = 'accuracy'
view_by = 'person'

## Base

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '1 - CNN - Base')
results['Base'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Base']

## Exclude Pain Level "0" from training

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '2 - CNN - Pain Gap')
results['Pain Level 0'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Pain Level 0']

## Use RMSProp as an optimizer instead of SGD

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '3 - CNN - RMS Prop')
results['RMSProp'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['RMSProp']

## ResNet Base

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '4 - ResNet - Base')
results['ResNet'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['ResNet']

## CNN - No Max Pooling After Last Conv2D Layer

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '5 - CNN - No MaxPool after Conv2D')
results['No Global Max Pooling'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['No Global Max Pooling']

## Convolution + Activation ReLU

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '6 - Activation')
results['ReLU'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['ReLU']

## Convolution + Batch Norm

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '7 - Batch Norm')
results['Batch Norm'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Batch Norm']

## Convolution + Batch Norm + ReLU

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '8 - Activation and Batch Norm')
results['ReLU + Batch Norm'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['ReLU + Batch Norm']

## Convolution + Batch Norm + ReLU

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '9 - Activation, Batch Norm, No Global MaxPool')
results['ReLU + Batch Norm + No Glob Max Pool'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['ReLU + Batch Norm + No Glob Max Pool']

## Convolution + Batch Norm + ReLU

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '10 - Replace Stride with Pooling')
results['Replace Stride with Pooling'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Replace Stride with Pooling']

## All Modifications

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '11 - All Modifications')
results['All Modifications'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['All Modifications']

## Personalization

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '12 - Personalization, Same Padding, Max Pool, Activation, Batch Norm')
results['Same Padding'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Same Padding']

## Joint Results - All Experiments

In [ ]:
result_df = pd.DataFrame()
for key, df in results.items():
    result_df[key] = df['Weighted Mean']
result_df

# SEEDS

## Seed 123

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '13 - Seed 123')
results['Seed 123'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Seed 123']

## Seed 124

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '14 - Seed 124')
results['Seed 124'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Seed 124']

## Seed 125

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '15 - Seed 125')
results['Seed 125'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Seed 125']

## Seed 131

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '131 - Seed 131')
results['Seed 131'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Seed 131']

In [ ]:
EXPERIMENT = os.path.join(RESULTS, '132 - Seed 132')
results['Seed 132'] = rE.results_table(EXPERIMENT, metric, view_by, subjects, pivot)
results['Seed 132']

# Average Seeds

In [34]:
average_results = rE.compute_average_metrics('person', subjects, pivot, RESULTS)

In [45]:
pd.options.display.float_format = '{:,.1f}'.format

In [53]:
EXPERIMENT = os.path.join(RESULTS, '132 - Seed 132')
results['TP'] = rE.results_table(EXPERIMENT, 'true_positives', 'individual', subjects, pivot)
results['FP'] = rE.results_table(EXPERIMENT, 'false_positives', 'individual', subjects, pivot)
results['TN'] = rE.results_table(EXPERIMENT, 'true_negatives', 'individual', subjects, pivot)
results['FN'] = rE.results_table(EXPERIMENT, 'false_negatives', 'individual', subjects, pivot)

## Pain Pivots

### By Person

In [58]:
dL.create_pivot(os.path.join(DATA, 'group_2'), 'Session', 'Person', 'Session')

Person    43   48   52   59   64    80    92   96   107  109  115  120  \
Session                                                                  
0        140        72       244  1052   464         32        60  116   
1             148       532   64   536   696             600             
2                             64   484              848       220        
3                                  484               60        56  188   
4        228                 248   660   724  112   828        60        
5             188                  792                   116             
6                   44             264        512                        
7                                                                        
8                  120                         88                        
9                  188                                                   
Total    368  336  424  532  620  4272  1884  712  1768  716  396  304   

Person   # of Persons   Pain  No Pain Pain %  
Session                                       
0                  12   2180    12424  15.0%  
1                  12   2576     8792  23.0%  
2                  11   1616     8756  16.0%  
3                  11    788     7696   9.0%  
4                  11   2860     7276  28.0%  
5                   9   1096     7380  13.0%  
6                   8    820     4852  14.0%  
7                   6            3788         
8                   3    208     3200   6.0%  
9                   1    188     1684  10.0%  
Total              84  12332    65848  16.0%

### By Session

In [57]:
dL.create_pivot(os.path.join(DATA, 'group_2'), 'Person', 'Session', 'Person')

Session     0     1     2    3     4     5    6 7    8    9  # of Sessions  \
Person                                                                       
52         72                                44    120  188             10   
43        140                    228                                     9   
96                               112        512     88                   9   
107        32         848   60   828                                     8   
109             600                    116                               8   
120       116              188                                           8   
48              148                    188                               7   
80       1052   536   484  484   660   792  264                          7   
64        244    64    64        248                                     6   
92        464   696              724                                     5   
115        60         220   56    60                                     5   
59              532                                                      2   
Total    2180  2576  1616  788  2860  1096  820    208  188             84   

Session   Pain  No Pain  Pain %  
Person                           
52         424    10012    4.0%  
43         368     4112    8.0%  
96         712     8700    8.0%  
107       1768     6396   22.0%  
109        716     6896    9.0%  
120        304     5960    5.0%  
48         336     3192   10.0%  
80        4272     3584   54.0%  
64         620     5576   10.0%  
92        1884     4124   31.0%  
115        396     4736    8.0%  
59         532     2560   17.0%  
Total    12332    65848   16.0%

In [59]:
# Create Dataframe
df = pd.DataFrame(dL.get_labels(dL.get_image_paths(os.path.join(DATA, 'group_2'))), columns=['Person', 'Session', 'Culture', 'Frame', 'Pain', 'Trans_1', 'Trans2'])
df[['Person', 'Session', 'Culture', 'Frame', 'Pain', ]] = df[['Person', 'Session', 'Culture', 'Frame', 'Pain', ]].astype(int)

# Get Frequencey values
sessions = sorted(df['Session'].unique())
share_1 = {}
for session in sessions:
    key, val = np.unique(df[df['Session'] == session]['Pain'], return_counts=True)
    if 1 in key:
        share_1[session] = val[1] / sum(val[1:])

In [79]:
np.unique(df[(df['Person'] == 52) & (df['Session'] == 0)]['Pain'], return_counts=True)

(array([0, 1, 2]), array([1424,   24,   48]))

In [75]:
np.unique(df[(df['Session'] == 4)]['Pain'], return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([7276,  800, 1388,  264,  176,   44,   20,   80,   32,   56]))

In [62]:
a = np.array([2180, 2576, 1616])
b = np.array([0.46, 0.31, 0.7])

In [66]:
c = a * b

In [67]:
d = a / b

In [69]:
sum(c[:2]) / sum(d[:2])

0.13804786001418776

In [72]:
sum(c) / sum(d)

0.19095445557575158